use crate::process::PermuteNodeName;

pub fn get_processor_display_name(name: PermuteNodeName) -> String {
    match name {
        PermuteNodeName::Reverse => String::from("Reverse"),
        PermuteNodeName::Chorus => String::from("Chorus"),
        PermuteNodeName::Phaser => String::from("Phaser"),
        PermuteNodeName::DoubleSpeed => String::from("Double Speed"),
        PermuteNodeName::HalfSpeed => String::from("Half Speed"),
        PermuteNodeName::RandomPitch => String::from("Random Pitch"),
        PermuteNodeName::GranularTimeStretch => String::from("Granular Stretch"),
        PermuteNodeName::Reverb => String::from("Reverb"),
        PermuteNodeName::Fuzz => String::from("Fuzz"),
        PermuteNodeName::Saturate => String::from("Saturate"),
        PermuteNodeName::Flutter => String::from("Flutter"),
        PermuteNodeName::Flange => String::from("Flange"),
        PermuteNodeName::MetallicDelay => String::from("Metallic Delay"),
        PermuteNodeName::RhythmicDelay => String::from("Rhythmic Delay"),
        PermuteNodeName::Wow => String::from("Wow"),
        PermuteNodeName::Normalise => String::from("Normalise"),
        PermuteNodeName::Trim => String::from("Trim"),
        PermuteNodeName::Tremolo => String::from("Tremolo"),
        PermuteNodeName::Lazer => String::from("Lazer"),
        PermuteNodeName::SampleRateConversionHigh => String::from("Sample rate conversion high"),
        PermuteNodeName::SampleRateConversionOriginal => String::from("Sample rate conversion low"),
        PermuteNodeName::Filter => String::from("Filter"),
        PermuteNodeName::OscillatingFilter => String::from("LFO Filter"),
        PermuteNodeName::LineFilter => String::from("Line Filter"),
        PermuteNodeName::CrossGain => String::from("Cross Gain"),
        PermuteNodeName::CrossFilter => String::from("Cross Filter"),
        PermuteNodeName::CrossDistort => String::from("Cross Distort"),
        PermuteNodeName::BlurStretch => String::from("Blur Stretch"),
    }
}

pub fn get_processor_from_display_name(name: &str) -> Result<PermuteNodeName, String> {
    match name {
        "Reverse" => Ok(PermuteNodeName::Reverse),
        "Chorus" => Ok(PermuteNodeName::Chorus),
        "Phaser" => Ok(PermuteNodeName::Phaser),
        "Double Speed" => Ok(PermuteNodeName::DoubleSpeed),
        "Flutter" => Ok(PermuteNodeName::Flutter),
        "Flange" => Ok(PermuteNodeName::Flange),
        "Half Speed" => Ok(PermuteNodeName::HalfSpeed),
        "Random Pitch" => Ok(PermuteNodeName::RandomPitch),
        "Metallic Delay" => Ok(PermuteNodeName::MetallicDelay),
        "Rhythmic Delay" => Ok(PermuteNodeName::RhythmicDelay),
        "Granular Stretch" => Ok(PermuteNodeName::GranularTimeStretch),
        "Reverb" => Ok(PermuteNodeName::Reverb),
        "Fuzz" => Ok(PermuteNodeName::Fuzz),
        "Saturate" => Ok(PermuteNodeName::Saturate),
        "Tremolo" => Ok(PermuteNodeName::Tremolo),
        "Lazer" => Ok(PermuteNodeName::Lazer),
        "Wow" => Ok(PermuteNodeName::Wow),
        "Normalise" => Ok(PermuteNodeName::Normalise),
        "Trim" => Ok(PermuteNodeName::Trim),
        "Sample rate conversion high" => Ok(PermuteNodeName::SampleRateConversionHigh),
        "Sample rate conversion low" => Ok(PermuteNodeName::SampleRateConversionOriginal),
        "Filter" => Ok(PermuteNodeName::Filter),
        "LFO Filter" => Ok(PermuteNodeName::OscillatingFilter),
        "Line Filter" => Ok(PermuteNodeName::LineFilter),
        "Cross Gain" => Ok(PermuteNodeName::CrossGain),
        "Cross Filter" => Ok(PermuteNodeName::CrossFilter),
        "Cross Distort" => Ok(PermuteNodeName::CrossDistort),
        "Blur Stretch" => Ok(PermuteNodeName::BlurStretch),
        _ => Err(format!("{} not found", name)),
    }
}
